# Generated by Django 5.2.1 on 2025-05-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_address_activity_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='member',
            new_name='user',
        ),
    ]
