# Generated by Django 5.2.1 on 2025-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_member_groupmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
    ]
