# Generated by Django 5.2.1 on 2025-06-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupmember_pending_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='pending_approval',
            new_name='is_pending_approval',
        ),
    ]
