# Generated by Django 5.2.1 on 2025-06-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_group_areas_user_interests_alter_group_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
    ]
