# Generated by Django 5.2.1 on 2025-06-06 04:04

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_interests'),
        ('tags', '0002_uuidtag_alter_relatedtag_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.UUIDTaggedItem', to='tags.UUIDTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='group',
            name='areas',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.UUIDTaggedItem', to='tags.UUIDTag', verbose_name='Tags'),
        ),
    ]
