# Generated by Django 5.2.1 on 2025-07-08 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDTag',
            fields=[
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tags.uuidtag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TagCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_source', to='tags.uuidtag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_target', to='tags.uuidtag')),
            ],
            options={
                'verbose_name': 'Tag Correlation',
                'verbose_name_plural': 'Tag Correlations',
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='RelatedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manually_related_to', to='tags.uuidtag')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_relations', to='tags.uuidtag')),
            ],
            options={
                'verbose_name': 'Related Tag',
                'verbose_name_plural': 'Related Tags',
                'unique_together': {('tag', 'related')},
            },
        ),
    ]
