# Generated by Django 5.2.1 on 2025-06-06 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manually_related_to', to='taggit.tag')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_relations', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Tag Relacionada (manual)',
                'verbose_name_plural': 'Tags Relacionadas (manuais)',
                'unique_together': {('tag', 'related')},
            },
        ),
        migrations.CreateModel(
            name='TagCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_source', to='taggit.tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_target', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Correlação de Tag (automática)',
                'verbose_name_plural': 'Correlações de Tags (automáticas)',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
